{
 "title": "Supervision Réseau & Sécurité – Temps Réel Copy",
 "description": "Ce tableau de bord a été conçu pour donner une vue d’ensemble opérationnelle et immédiate d'un  infrastructure réseau et de l’activité de sécurité",
 "time": { "from": "2025-06-08T16:05:15.516Z", "to": "2025-06-08T16:25:15.516Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "pourcentage de vos flux jugés propres",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  100.0 * SUM(CASE WHEN attack = FALSE THEN 1 ELSE 0 END)\n    / NULLIF(COUNT(*), 0)                     AS clean_pct\nFROM flow_aggregates\nWHERE window_start >= NOW() - INTERVAL '30 minutes'\n\n"
    }
   ]
  },
  {
   "title": "Débit moyen (Mbps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(window_start, '5s') AS time,\n  SUM(total_bytes)  AS mbps\nFROM flow_aggregates\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Temps de réponse moyen du réseaux (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(window_start, '60s') AS time,\n  AVG(duration_ms)                   AS rtt_ms\nFROM flow_aggregates\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "5 ports les plus volumineux",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  dport::text AS port,\n  SUM(total_bytes) AS bytes_total\nFROM flow_aggregates\nWHERE $__timeFilter(window_start)\nGROUP BY dport\nORDER BY bytes_total DESC\nLIMIT 5\n\n"
    }
   ]
  }
 ]
}